/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'topic-tags': TopicTag;
    words: Word;
    'grammar-topics': GrammarTopic;
    scenarios: Scenario;
    feedback: Feedback;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'topic-tags': TopicTagsSelect<false> | TopicTagsSelect<true>;
    words: WordsSelect<false> | WordsSelect<true>;
    'grammar-topics': GrammarTopicsSelect<false> | GrammarTopicsSelect<true>;
    scenarios: ScenariosSelect<false> | ScenariosSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  role: 'admin' | 'editor' | 'learner';
  accountStatus: 'active' | 'suspended';
  uiLocale: 'en' | 'bn';
  supportMode: 'en' | 'bn' | 'both';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic-tags".
 */
export interface TopicTag {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  english: {
    description: string;
  };
  bangla?: {
    description?: string | null;
  };
  parent?: (number | null) | TopicTag;
  sortOrder: number;
  review?: {
    germanReviewed?: boolean | null;
    englishReviewed?: boolean | null;
    banglaReviewed?: boolean | null;
  };
  source?: {
    attribution?: string | null;
    sourceUrl?: string | null;
    licenseName?: string | null;
    licenseUrl?: string | null;
    usageNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create and review German vocabulary with independent English and Bangla learner support.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "words".
 */
export interface Word {
  id: number;
  /**
   * Use the dictionary headword, including the article for nouns. The locked public URL slug follows this value.
   */
  lemma: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Choose the grammatical category used to reveal relevant fields and public labels.
   */
  wordType: 'noun' | 'verb' | 'adjective' | 'adverb' | 'preposition' | 'conjunction' | 'phrase' | 'idiom';
  /**
   * Choose the earliest CEFR level at which this word should be introduced.
   */
  cefrLevel: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  /**
   * Select the definite article that identifies the noun gender.
   */
  gender?: ('der' | 'die' | 'das') | null;
  /**
   * Enter the complete plural form, including the article when useful.
   */
  pluralForm?: string | null;
  /**
   * Use a standard German IPA transcription, including slashes when appropriate.
   */
  ipa?: string | null;
  /**
   * Describe the social or stylistic context in which the word is normally used.
   */
  register: 'neutral' | 'formal' | 'informal' | 'slang' | 'academic' | 'official' | 'rude' | 'poetic' | 'archaic';
  /**
   * Rate practical learning value from 1 (specialized) to 5 (essential).
   */
  usefulnessScore: number;
  english: {
    /**
     * Add at least one concise, non-empty English meaning before publishing.
     */
    meanings: {
      meaning: string;
      id?: string | null;
    }[];
    /**
     * Explain usage in clear language appropriate for the selected CEFR level.
     */
    explanation?: string | null;
    commonMistakes?:
      | {
          mistake: string;
          id?: string | null;
        }[]
      | null;
  };
  bangla?: {
    meanings?:
      | {
          meaning: string;
          id?: string | null;
        }[]
      | null;
    explanation?: string | null;
    pronunciationHints?:
      | {
          hint: string;
          id?: string | null;
        }[]
      | null;
    commonMistakes?:
      | {
          mistake: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional search or onboarding aid; Bangla script remains the primary learner content.
     */
    romanizedHelper?: string | null;
  };
  /**
   * English is required for each example. Bangla is optional and follows the word-level Bangla review gate.
   */
  examples?:
    | {
        germanSentence: string;
        englishExplanation: string;
        banglaExplanation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose every topic under which learners should be able to discover this word.
   */
  topicTags?: (number | TopicTag)[] | null;
  /**
   * Choose published vocabulary that helps learners build a useful semantic or situational connection.
   */
  relatedWords?: (number | Word)[] | null;
  /**
   * Record attribution, URLs, licensing, and any restrictions before reusing sourced material.
   */
  source?: {
    attribution?: string | null;
    sourceUrl?: string | null;
    licenseName?: string | null;
    licenseUrl?: string | null;
    usageNotes?: string | null;
  };
  /**
   * Archive instead of deleting: archived words disappear from public pages while versions and references remain intact.
   */
  lifecycleStatus: 'active' | 'archived';
  /**
   * Review flags are independent. Bangla remains hidden publicly until Bangla reviewed is enabled.
   */
  review?: {
    germanReviewed?: boolean | null;
    englishReviewed?: boolean | null;
    banglaReviewed?: boolean | null;
    audioReviewed?: boolean | null;
    quizReviewed?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Explain German grammar patterns with independent English and Bangla learner support.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grammar-topics".
 */
export interface GrammarTopic {
  id: number;
  /**
   * Use the conventional German grammar term, for example "Perfekt mit haben und sein".
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Choose the earliest CEFR level at which this pattern should be taught.
   */
  cefrLevel: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  /**
   * State the rule in one German sentence. Learners see this before the full explanation.
   */
  shortRule: string;
  english: {
    /**
     * Explain when and how the pattern is used. Use short headings and lists rather than long paragraphs.
     */
    explanation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    commonMistakes?:
      | {
          mistake: string;
          id?: string | null;
        }[]
      | null;
  };
  bangla?: {
    explanation?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    commonMistakes?:
      | {
          mistake: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * English is required for each example. Bangla is optional and follows the topic-level Bangla review gate.
   */
  examples?:
    | {
        germanSentence: string;
        englishExplanation: string;
        banglaExplanation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose every topic under which learners should be able to discover this pattern.
   */
  topicTags?: (number | TopicTag)[] | null;
  /**
   * Choose published vocabulary that demonstrates this pattern. These words link back to this topic.
   */
  relatedWords?: (number | Word)[] | null;
  /**
   * Record attribution, URLs, licensing, and any restrictions before reusing sourced material.
   */
  source?: {
    attribution?: string | null;
    sourceUrl?: string | null;
    licenseName?: string | null;
    licenseUrl?: string | null;
    usageNotes?: string | null;
  };
  /**
   * Review flags are independent. Bangla remains hidden publicly until Bangla reviewed is enabled.
   */
  review?: {
    germanReviewed?: boolean | null;
    englishReviewed?: boolean | null;
    banglaReviewed?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Build real-world German dialogues with independent English and Bangla learner support.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios".
 */
export interface Scenario {
  id: number;
  /**
   * Name the situation in German, for example "Im Café bestellen".
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Choose the earliest CEFR level at which a learner could hold this conversation.
   */
  cefrLevel: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  /**
   * Pick the everyday domain this conversation belongs to. Learners filter the scenario index by this value.
   */
  situationType: 'everyday' | 'travel' | 'work' | 'study' | 'health' | 'services' | 'social';
  /**
   * State the goal in one German sentence, for example "Ich kann ein Getränk höflich bestellen." Learners see this before the dialogue.
   */
  learnerGoal: string;
  english: {
    /**
     * Explain how the conversation works and which phrases carry it. Use short headings and lists rather than long paragraphs.
     */
    explanation: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Note the expectations a learner would not guess, such as greetings, formality, or tipping.
     */
    culturalNotes?:
      | {
          note: string;
          id?: string | null;
        }[]
      | null;
  };
  bangla?: {
    explanation?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    culturalNotes?:
      | {
          note: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * English is required for each line. Bangla is optional and follows the scenario-level Bangla review gate.
   */
  dialogue?:
    | {
        /**
         * Name the speaker in German, for example "Kundin" or "Kellner".
         */
        speaker: string;
        germanLine: string;
        englishExplanation: string;
        banglaExplanation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose every topic under which learners should be able to discover this scenario.
   */
  topicTags?: (number | TopicTag)[] | null;
  /**
   * Choose published vocabulary a learner needs for this conversation. These words link back to this scenario.
   */
  keyVocabulary?: (number | Word)[] | null;
  /**
   * Choose published grammar patterns this dialogue practises. These topics link back to this scenario.
   */
  relatedGrammarTopics?: (number | GrammarTopic)[] | null;
  /**
   * Record attribution, URLs, licensing, and any restrictions before reusing sourced material.
   */
  source?: {
    attribution?: string | null;
    sourceUrl?: string | null;
    licenseName?: string | null;
    licenseUrl?: string | null;
    usageNotes?: string | null;
  };
  /**
   * Review flags are independent. Bangla remains hidden publicly until Bangla reviewed is enabled.
   */
  review?: {
    germanReviewed?: boolean | null;
    englishReviewed?: boolean | null;
    banglaReviewed?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Learner-reported problems with published content. Submissions arrive as New; triage them and record what happened in the moderation notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  /**
   * Which kind of page the report came from.
   */
  contentType: 'word' | 'grammar-topic' | 'scenario';
  /**
   * What the reporter said was wrong.
   */
  feedbackType:
    | 'incorrect-german'
    | 'incorrect-english'
    | 'incorrect-bangla'
    | 'missing-audio'
    | 'bad-example'
    | 'wrong-cefr'
    | 'unclear-explanation'
    | 'usage-suggestion'
    | 'other';
  /**
   * The reported document, for one-click navigation.
   */
  related:
    | {
        relationTo: 'words';
        value: number | Word;
      }
    | {
        relationTo: 'grammar-topics';
        value: number | GrammarTopic;
      }
    | {
        relationTo: 'scenarios';
        value: number | Scenario;
      };
  /**
   * Snapshot of the slug at submission time, so the queue stays readable if the content is later renamed or removed.
   */
  relatedSlug: string;
  /**
   * What the reporter wrote, stored verbatim.
   */
  message: string;
  /**
   * Optional reply address. Personal data — visible to admins only.
   */
  email?: string | null;
  /**
   * Interface language the report was written in.
   */
  submitterLocale?: ('en' | 'bn') | null;
  /**
   * Every submission starts as New.
   */
  status: 'new' | 'triaged' | 'resolved' | 'rejected';
  /**
   * Internal only. Never shown to the reporter.
   */
  adminNotes?: string | null;
  /**
   * Set automatically when the status changes.
   */
  handledBy?: (number | null) | User;
  /**
   * Set automatically when the status changes.
   */
  handledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'topic-tags';
        value: number | TopicTag;
      } | null)
    | ({
        relationTo: 'words';
        value: number | Word;
      } | null)
    | ({
        relationTo: 'grammar-topics';
        value: number | GrammarTopic;
      } | null)
    | ({
        relationTo: 'scenarios';
        value: number | Scenario;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  accountStatus?: T;
  uiLocale?: T;
  supportMode?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic-tags_select".
 */
export interface TopicTagsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  english?:
    | T
    | {
        description?: T;
      };
  bangla?:
    | T
    | {
        description?: T;
      };
  parent?: T;
  sortOrder?: T;
  review?:
    | T
    | {
        germanReviewed?: T;
        englishReviewed?: T;
        banglaReviewed?: T;
      };
  source?:
    | T
    | {
        attribution?: T;
        sourceUrl?: T;
        licenseName?: T;
        licenseUrl?: T;
        usageNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "words_select".
 */
export interface WordsSelect<T extends boolean = true> {
  lemma?: T;
  generateSlug?: T;
  slug?: T;
  wordType?: T;
  cefrLevel?: T;
  gender?: T;
  pluralForm?: T;
  ipa?: T;
  register?: T;
  usefulnessScore?: T;
  english?:
    | T
    | {
        meanings?:
          | T
          | {
              meaning?: T;
              id?: T;
            };
        explanation?: T;
        commonMistakes?:
          | T
          | {
              mistake?: T;
              id?: T;
            };
      };
  bangla?:
    | T
    | {
        meanings?:
          | T
          | {
              meaning?: T;
              id?: T;
            };
        explanation?: T;
        pronunciationHints?:
          | T
          | {
              hint?: T;
              id?: T;
            };
        commonMistakes?:
          | T
          | {
              mistake?: T;
              id?: T;
            };
        romanizedHelper?: T;
      };
  examples?:
    | T
    | {
        germanSentence?: T;
        englishExplanation?: T;
        banglaExplanation?: T;
        id?: T;
      };
  topicTags?: T;
  relatedWords?: T;
  source?:
    | T
    | {
        attribution?: T;
        sourceUrl?: T;
        licenseName?: T;
        licenseUrl?: T;
        usageNotes?: T;
      };
  lifecycleStatus?: T;
  review?:
    | T
    | {
        germanReviewed?: T;
        englishReviewed?: T;
        banglaReviewed?: T;
        audioReviewed?: T;
        quizReviewed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grammar-topics_select".
 */
export interface GrammarTopicsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  cefrLevel?: T;
  shortRule?: T;
  english?:
    | T
    | {
        explanation?: T;
        commonMistakes?:
          | T
          | {
              mistake?: T;
              id?: T;
            };
      };
  bangla?:
    | T
    | {
        explanation?: T;
        commonMistakes?:
          | T
          | {
              mistake?: T;
              id?: T;
            };
      };
  examples?:
    | T
    | {
        germanSentence?: T;
        englishExplanation?: T;
        banglaExplanation?: T;
        id?: T;
      };
  topicTags?: T;
  relatedWords?: T;
  source?:
    | T
    | {
        attribution?: T;
        sourceUrl?: T;
        licenseName?: T;
        licenseUrl?: T;
        usageNotes?: T;
      };
  review?:
    | T
    | {
        germanReviewed?: T;
        englishReviewed?: T;
        banglaReviewed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios_select".
 */
export interface ScenariosSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  cefrLevel?: T;
  situationType?: T;
  learnerGoal?: T;
  english?:
    | T
    | {
        explanation?: T;
        culturalNotes?:
          | T
          | {
              note?: T;
              id?: T;
            };
      };
  bangla?:
    | T
    | {
        explanation?: T;
        culturalNotes?:
          | T
          | {
              note?: T;
              id?: T;
            };
      };
  dialogue?:
    | T
    | {
        speaker?: T;
        germanLine?: T;
        englishExplanation?: T;
        banglaExplanation?: T;
        id?: T;
      };
  topicTags?: T;
  keyVocabulary?: T;
  relatedGrammarTopics?: T;
  source?:
    | T
    | {
        attribution?: T;
        sourceUrl?: T;
        licenseName?: T;
        licenseUrl?: T;
        usageNotes?: T;
      };
  review?:
    | T
    | {
        germanReviewed?: T;
        englishReviewed?: T;
        banglaReviewed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  contentType?: T;
  feedbackType?: T;
  related?: T;
  relatedSlug?: T;
  message?: T;
  email?: T;
  submitterLocale?: T;
  status?: T;
  adminNotes?: T;
  handledBy?: T;
  handledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}