/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'topic-tags': TopicTag;
    words: Word;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'topic-tags': TopicTagsSelect<false> | TopicTagsSelect<true>;
    words: WordsSelect<false> | WordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  role: 'admin' | 'editor' | 'learner';
  accountStatus: 'active' | 'suspended';
  uiLocale: 'en' | 'bn';
  supportMode: 'en' | 'bn' | 'both';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic-tags".
 */
export interface TopicTag {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  english: {
    description: string;
  };
  bangla?: {
    description?: string | null;
  };
  parent?: (number | null) | TopicTag;
  sortOrder: number;
  review?: {
    germanReviewed?: boolean | null;
    englishReviewed?: boolean | null;
    banglaReviewed?: boolean | null;
  };
  source?: {
    attribution?: string | null;
    sourceUrl?: string | null;
    licenseName?: string | null;
    licenseUrl?: string | null;
    usageNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "words".
 */
export interface Word {
  id: number;
  lemma: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  wordType: 'noun' | 'verb' | 'adjective' | 'adverb' | 'preposition' | 'conjunction' | 'phrase' | 'idiom';
  cefrLevel: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  gender?: ('der' | 'die' | 'das') | null;
  pluralForm?: string | null;
  ipa?: string | null;
  register: 'neutral' | 'formal' | 'informal' | 'slang' | 'academic' | 'official' | 'rude' | 'poetic' | 'archaic';
  usefulnessScore: number;
  topicTags?: (number | TopicTag)[] | null;
  english: {
    meanings: {
      meaning: string;
      id?: string | null;
    }[];
    explanation?: string | null;
    commonMistakes?:
      | {
          mistake: string;
          id?: string | null;
        }[]
      | null;
  };
  bangla?: {
    meanings?:
      | {
          meaning: string;
          id?: string | null;
        }[]
      | null;
    explanation?: string | null;
    pronunciationHints?:
      | {
          hint: string;
          id?: string | null;
        }[]
      | null;
    commonMistakes?:
      | {
          mistake: string;
          id?: string | null;
        }[]
      | null;
    romanizedHelper?: string | null;
  };
  examples?:
    | {
        germanSentence: string;
        englishExplanation: string;
        banglaExplanation?: string | null;
        id?: string | null;
      }[]
    | null;
  review?: {
    germanReviewed?: boolean | null;
    englishReviewed?: boolean | null;
    banglaReviewed?: boolean | null;
    audioReviewed?: boolean | null;
    quizReviewed?: boolean | null;
  };
  source?: {
    attribution?: string | null;
    sourceUrl?: string | null;
    licenseName?: string | null;
    licenseUrl?: string | null;
    usageNotes?: string | null;
  };
  lifecycleStatus: 'active' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'topic-tags';
        value: number | TopicTag;
      } | null)
    | ({
        relationTo: 'words';
        value: number | Word;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  accountStatus?: T;
  uiLocale?: T;
  supportMode?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic-tags_select".
 */
export interface TopicTagsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  english?:
    | T
    | {
        description?: T;
      };
  bangla?:
    | T
    | {
        description?: T;
      };
  parent?: T;
  sortOrder?: T;
  review?:
    | T
    | {
        germanReviewed?: T;
        englishReviewed?: T;
        banglaReviewed?: T;
      };
  source?:
    | T
    | {
        attribution?: T;
        sourceUrl?: T;
        licenseName?: T;
        licenseUrl?: T;
        usageNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "words_select".
 */
export interface WordsSelect<T extends boolean = true> {
  lemma?: T;
  generateSlug?: T;
  slug?: T;
  wordType?: T;
  cefrLevel?: T;
  gender?: T;
  pluralForm?: T;
  ipa?: T;
  register?: T;
  usefulnessScore?: T;
  topicTags?: T;
  english?:
    | T
    | {
        meanings?:
          | T
          | {
              meaning?: T;
              id?: T;
            };
        explanation?: T;
        commonMistakes?:
          | T
          | {
              mistake?: T;
              id?: T;
            };
      };
  bangla?:
    | T
    | {
        meanings?:
          | T
          | {
              meaning?: T;
              id?: T;
            };
        explanation?: T;
        pronunciationHints?:
          | T
          | {
              hint?: T;
              id?: T;
            };
        commonMistakes?:
          | T
          | {
              mistake?: T;
              id?: T;
            };
        romanizedHelper?: T;
      };
  examples?:
    | T
    | {
        germanSentence?: T;
        englishExplanation?: T;
        banglaExplanation?: T;
        id?: T;
      };
  review?:
    | T
    | {
        germanReviewed?: T;
        englishReviewed?: T;
        banglaReviewed?: T;
        audioReviewed?: T;
        quizReviewed?: T;
      };
  source?:
    | T
    | {
        attribution?: T;
        sourceUrl?: T;
        licenseName?: T;
        licenseUrl?: T;
        usageNotes?: T;
      };
  lifecycleStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}